# Generated by Django 4.2.4 on 2024-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmodel',
            name='encoding_type',
            field=models.CharField(blank=True, choices=[('ONE_HOT', 'One Hot'), ('LABEL', 'Label')], default='ONE_HOT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='columnmodel',
            name='scaling_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('MIN_MAX', 'Min Max'), ('MAX_ABS', 'Max Abs'), ('ROBUST', 'Robust'), ('NORMALIZER', 'Normalizer')], default='STANDARD', max_length=100, null=True),
        ),
    ]
