# Generated by Django 4.2.4 on 2023-08-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmodel',
            name='hyperparameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
