# Generated by Django 4.2.4 on 2023-08-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_control', '0002_trainmodel_hyperparameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Column Model', 'verbose_name_plural': 'Column Models'},
        ),
    ]
