# Generated by Django 4.2.4 on 2023-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_control', '0003_alter_columnmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmodel',
            name='test_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
