# Generated by Django 4.2.4 on 2023-08-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_control', '0004_trainmodel_test_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columnmodel',
            options={'ordering': ['created_at'], 'verbose_name': 'Column Model', 'verbose_name_plural': 'Column Models'},
        ),
    ]
